repository:
  name: .github
  private: false
  visibility: "public"
  has_issues: false
  has_projects: false
  has_wiki: false
  default_branch: "main"
  gitignore_template: null
  license_template: null
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  archived: false
  security:
    enableAutomatedSecurityFixes: true
